[package]
description = "A port of Mojang's Authlib and launcher authentication."
edition = "2021"
license = "MIT"
name = "azalea-auth"
repository = "https://github.com/mat-1/azalea/tree/main/azalea-auth"
version = "0.7.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
azalea-buf = { path = "../azalea-buf", version = "^0.7.0" }
azalea-crypto = { path = "../azalea-crypto", version = "^0.7.0" }
base64 = "0.21.0"
chrono = { version = "0.4.24", default-features = false, features = ["serde"] }
log = "0.4.17"
num-bigint = "0.4.3"
once_cell = "1.17.1"
parking_lot = "0.12.1"
reqwest = { version = "0.11.16", default-features = false, features = [
    "json",
    "rustls-tls",
] }
rsa = "0.9.2"
serde = { version = "1.0.159", features = ["derive"] }
serde_json = "1.0.95"
thiserror = "1.0.40"
tokio = { version = "1.27.0", features = ["fs"] }
uuid = { version = "1.3.0", features = ["serde"] }

[dev-dependencies]
env_logger = "0.10.0"
tokio = { version = "1.27.0", features = ["full"] }
